# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/otus_cpp_p_project/otus_cpp_p_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/otus_cpp_p_project/otus_cpp_p_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/runner/work/otus_cpp_p_project/otus_cpp_p_project/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/otus_cpp_p_project/otus_cpp_p_project/CMakeFiles /home/runner/work/otus_cpp_p_project/otus_cpp_p_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/otus_cpp_p_project/otus_cpp_p_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named halfSumFinder.exe

# Build rule for target.
halfSumFinder.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 halfSumFinder.exe
.PHONY : halfSumFinder.exe

# fast build rule for target.
halfSumFinder.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/halfSumFinder.exe.dir/build.make CMakeFiles/halfSumFinder.exe.dir/build
.PHONY : halfSumFinder.exe/fast

#=============================================================================
# Target rules for targets named hsfTester.exe

# Build rule for target.
hsfTester.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hsfTester.exe
.PHONY : hsfTester.exe

# fast build rule for target.
hsfTester.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/build
.PHONY : hsfTester.exe/fast

#=============================================================================
# Target rules for targets named hsfSearchOrderDemo.exe

# Build rule for target.
hsfSearchOrderDemo.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hsfSearchOrderDemo.exe
.PHONY : hsfSearchOrderDemo.exe

# fast build rule for target.
hsfSearchOrderDemo.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfSearchOrderDemo.exe.dir/build.make CMakeFiles/hsfSearchOrderDemo.exe.dir/build
.PHONY : hsfSearchOrderDemo.exe/fast

#=============================================================================
# Target rules for targets named hsfInputGenerator.exe

# Build rule for target.
hsfInputGenerator.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hsfInputGenerator.exe
.PHONY : hsfInputGenerator.exe

# fast build rule for target.
hsfInputGenerator.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfInputGenerator.exe.dir/build.make CMakeFiles/hsfInputGenerator.exe.dir/build
.PHONY : hsfInputGenerator.exe/fast

#=============================================================================
# Target rules for targets named hsfOutputVerifier.exe

# Build rule for target.
hsfOutputVerifier.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hsfOutputVerifier.exe
.PHONY : hsfOutputVerifier.exe

# fast build rule for target.
hsfOutputVerifier.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfOutputVerifier.exe.dir/build.make CMakeFiles/hsfOutputVerifier.exe.dir/build
.PHONY : hsfOutputVerifier.exe/fast

halfSumFinder/main.o: halfSumFinder/main.cpp.o
.PHONY : halfSumFinder/main.o

# target to build an object file
halfSumFinder/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/halfSumFinder.exe.dir/build.make CMakeFiles/halfSumFinder.exe.dir/halfSumFinder/main.cpp.o
.PHONY : halfSumFinder/main.cpp.o

halfSumFinder/main.i: halfSumFinder/main.cpp.i
.PHONY : halfSumFinder/main.i

# target to preprocess a source file
halfSumFinder/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/halfSumFinder.exe.dir/build.make CMakeFiles/halfSumFinder.exe.dir/halfSumFinder/main.cpp.i
.PHONY : halfSumFinder/main.cpp.i

halfSumFinder/main.s: halfSumFinder/main.cpp.s
.PHONY : halfSumFinder/main.s

# target to generate assembly for a file
halfSumFinder/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/halfSumFinder.exe.dir/build.make CMakeFiles/halfSumFinder.exe.dir/halfSumFinder/main.cpp.s
.PHONY : halfSumFinder/main.cpp.s

hsfInputGenerator/main.o: hsfInputGenerator/main.cpp.o
.PHONY : hsfInputGenerator/main.o

# target to build an object file
hsfInputGenerator/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfInputGenerator.exe.dir/build.make CMakeFiles/hsfInputGenerator.exe.dir/hsfInputGenerator/main.cpp.o
.PHONY : hsfInputGenerator/main.cpp.o

hsfInputGenerator/main.i: hsfInputGenerator/main.cpp.i
.PHONY : hsfInputGenerator/main.i

# target to preprocess a source file
hsfInputGenerator/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfInputGenerator.exe.dir/build.make CMakeFiles/hsfInputGenerator.exe.dir/hsfInputGenerator/main.cpp.i
.PHONY : hsfInputGenerator/main.cpp.i

hsfInputGenerator/main.s: hsfInputGenerator/main.cpp.s
.PHONY : hsfInputGenerator/main.s

# target to generate assembly for a file
hsfInputGenerator/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfInputGenerator.exe.dir/build.make CMakeFiles/hsfInputGenerator.exe.dir/hsfInputGenerator/main.cpp.s
.PHONY : hsfInputGenerator/main.cpp.s

hsfOutputVerifier/main.o: hsfOutputVerifier/main.cpp.o
.PHONY : hsfOutputVerifier/main.o

# target to build an object file
hsfOutputVerifier/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfOutputVerifier.exe.dir/build.make CMakeFiles/hsfOutputVerifier.exe.dir/hsfOutputVerifier/main.cpp.o
.PHONY : hsfOutputVerifier/main.cpp.o

hsfOutputVerifier/main.i: hsfOutputVerifier/main.cpp.i
.PHONY : hsfOutputVerifier/main.i

# target to preprocess a source file
hsfOutputVerifier/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfOutputVerifier.exe.dir/build.make CMakeFiles/hsfOutputVerifier.exe.dir/hsfOutputVerifier/main.cpp.i
.PHONY : hsfOutputVerifier/main.cpp.i

hsfOutputVerifier/main.s: hsfOutputVerifier/main.cpp.s
.PHONY : hsfOutputVerifier/main.s

# target to generate assembly for a file
hsfOutputVerifier/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfOutputVerifier.exe.dir/build.make CMakeFiles/hsfOutputVerifier.exe.dir/hsfOutputVerifier/main.cpp.s
.PHONY : hsfOutputVerifier/main.cpp.s

hsfSearchOrderDemo/main.o: hsfSearchOrderDemo/main.cpp.o
.PHONY : hsfSearchOrderDemo/main.o

# target to build an object file
hsfSearchOrderDemo/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfSearchOrderDemo.exe.dir/build.make CMakeFiles/hsfSearchOrderDemo.exe.dir/hsfSearchOrderDemo/main.cpp.o
.PHONY : hsfSearchOrderDemo/main.cpp.o

hsfSearchOrderDemo/main.i: hsfSearchOrderDemo/main.cpp.i
.PHONY : hsfSearchOrderDemo/main.i

# target to preprocess a source file
hsfSearchOrderDemo/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfSearchOrderDemo.exe.dir/build.make CMakeFiles/hsfSearchOrderDemo.exe.dir/hsfSearchOrderDemo/main.cpp.i
.PHONY : hsfSearchOrderDemo/main.cpp.i

hsfSearchOrderDemo/main.s: hsfSearchOrderDemo/main.cpp.s
.PHONY : hsfSearchOrderDemo/main.s

# target to generate assembly for a file
hsfSearchOrderDemo/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfSearchOrderDemo.exe.dir/build.make CMakeFiles/hsfSearchOrderDemo.exe.dir/hsfSearchOrderDemo/main.cpp.s
.PHONY : hsfSearchOrderDemo/main.cpp.s

hsfTester/main.o: hsfTester/main.cpp.o
.PHONY : hsfTester/main.o

# target to build an object file
hsfTester/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/hsfTester/main.cpp.o
.PHONY : hsfTester/main.cpp.o

hsfTester/main.i: hsfTester/main.cpp.i
.PHONY : hsfTester/main.i

# target to preprocess a source file
hsfTester/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/hsfTester/main.cpp.i
.PHONY : hsfTester/main.cpp.i

hsfTester/main.s: hsfTester/main.cpp.s
.PHONY : hsfTester/main.s

# target to generate assembly for a file
hsfTester/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/hsfTester/main.cpp.s
.PHONY : hsfTester/main.cpp.s

src/halfsumfinder.o: src/halfsumfinder.cpp.o
.PHONY : src/halfsumfinder.o

# target to build an object file
src/halfsumfinder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/halfSumFinder.exe.dir/build.make CMakeFiles/halfSumFinder.exe.dir/src/halfsumfinder.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/src/halfsumfinder.cpp.o
.PHONY : src/halfsumfinder.cpp.o

src/halfsumfinder.i: src/halfsumfinder.cpp.i
.PHONY : src/halfsumfinder.i

# target to preprocess a source file
src/halfsumfinder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/halfSumFinder.exe.dir/build.make CMakeFiles/halfSumFinder.exe.dir/src/halfsumfinder.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/src/halfsumfinder.cpp.i
.PHONY : src/halfsumfinder.cpp.i

src/halfsumfinder.s: src/halfsumfinder.cpp.s
.PHONY : src/halfsumfinder.s

# target to generate assembly for a file
src/halfsumfinder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/halfSumFinder.exe.dir/build.make CMakeFiles/halfSumFinder.exe.dir/src/halfsumfinder.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/src/halfsumfinder.cpp.s
.PHONY : src/halfsumfinder.cpp.s

src/set.o: src/set.cpp.o
.PHONY : src/set.o

# target to build an object file
src/set.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/halfSumFinder.exe.dir/build.make CMakeFiles/halfSumFinder.exe.dir/src/set.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/src/set.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfSearchOrderDemo.exe.dir/build.make CMakeFiles/hsfSearchOrderDemo.exe.dir/src/set.cpp.o
.PHONY : src/set.cpp.o

src/set.i: src/set.cpp.i
.PHONY : src/set.i

# target to preprocess a source file
src/set.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/halfSumFinder.exe.dir/build.make CMakeFiles/halfSumFinder.exe.dir/src/set.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/src/set.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfSearchOrderDemo.exe.dir/build.make CMakeFiles/hsfSearchOrderDemo.exe.dir/src/set.cpp.i
.PHONY : src/set.cpp.i

src/set.s: src/set.cpp.s
.PHONY : src/set.s

# target to generate assembly for a file
src/set.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/halfSumFinder.exe.dir/build.make CMakeFiles/halfSumFinder.exe.dir/src/set.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/src/set.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfSearchOrderDemo.exe.dir/build.make CMakeFiles/hsfSearchOrderDemo.exe.dir/src/set.cpp.s
.PHONY : src/set.cpp.s

util/gendata.o: util/gendata.cpp.o
.PHONY : util/gendata.o

# target to build an object file
util/gendata.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/util/gendata.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfInputGenerator.exe.dir/build.make CMakeFiles/hsfInputGenerator.exe.dir/util/gendata.cpp.o
.PHONY : util/gendata.cpp.o

util/gendata.i: util/gendata.cpp.i
.PHONY : util/gendata.i

# target to preprocess a source file
util/gendata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/util/gendata.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfInputGenerator.exe.dir/build.make CMakeFiles/hsfInputGenerator.exe.dir/util/gendata.cpp.i
.PHONY : util/gendata.cpp.i

util/gendata.s: util/gendata.cpp.s
.PHONY : util/gendata.s

# target to generate assembly for a file
util/gendata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfTester.exe.dir/build.make CMakeFiles/hsfTester.exe.dir/util/gendata.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hsfInputGenerator.exe.dir/build.make CMakeFiles/hsfInputGenerator.exe.dir/util/gendata.cpp.s
.PHONY : util/gendata.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... halfSumFinder.exe"
	@echo "... hsfInputGenerator.exe"
	@echo "... hsfOutputVerifier.exe"
	@echo "... hsfSearchOrderDemo.exe"
	@echo "... hsfTester.exe"
	@echo "... halfSumFinder/main.o"
	@echo "... halfSumFinder/main.i"
	@echo "... halfSumFinder/main.s"
	@echo "... hsfInputGenerator/main.o"
	@echo "... hsfInputGenerator/main.i"
	@echo "... hsfInputGenerator/main.s"
	@echo "... hsfOutputVerifier/main.o"
	@echo "... hsfOutputVerifier/main.i"
	@echo "... hsfOutputVerifier/main.s"
	@echo "... hsfSearchOrderDemo/main.o"
	@echo "... hsfSearchOrderDemo/main.i"
	@echo "... hsfSearchOrderDemo/main.s"
	@echo "... hsfTester/main.o"
	@echo "... hsfTester/main.i"
	@echo "... hsfTester/main.s"
	@echo "... src/halfsumfinder.o"
	@echo "... src/halfsumfinder.i"
	@echo "... src/halfsumfinder.s"
	@echo "... src/set.o"
	@echo "... src/set.i"
	@echo "... src/set.s"
	@echo "... util/gendata.o"
	@echo "... util/gendata.i"
	@echo "... util/gendata.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

